# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      "GitHub Actions updates":
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/rss_generator"
    schedule:
      interval: "monthly"
    groups:
      "Go modules updates":
        dependency-type: "production"
  - package-ecosystem: "gomod"
    directory: "/publisher"
    schedule:
      interval: "monthly"
    groups:
      "Go modules updates":
        dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/hugo"
    schedule:
      interval: "monthly"
    groups:
      "NPM modules updates":
        dependency-type: "production"
      "NPM development modules updates":
        dependency-type: "development"
